# Site settings
title: 2lazy2late blog
url: "https://2lazy2late.github.io"
baseurl: ""
description: >
    2lazy2late blog

# My information
email: rainyskin@gmail.com
author: 2lazy2late
profile: 2lazy2late-prof
twitter_username: pontneuf
github_username: 2lazy2late
comment-support: utterances

# Build settings
plugins:
  - jekyll-paginate
  - jekyll-gist

permalink: /blog/:year/:month/:day/:title/

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge

paginate: 10
paginator_path: "/blog"
paginate_path: "/blog/page:num/"

# Collections
collections:
    wiki:
        output: true
        permalink: /:collection/:path/

# Comment Service
disqus:
  id: 2lazy2late
  shortname: 2lazy2late
utterances:
  repo: 2lazy2late/2lazy2late.github.io
  issue-term: url
  label: Comment
  branch: master

google_analytics:
  ua: UA-110224147-1

google_adsense:
  client: ca-pub-8094053398508289

blame: "https://github.com/2lazy2late/2lazy2late.github.io/blame/master/_wiki"
edit: "https://github.com/2lazy2late/2lazy2late.github.io/edit/master/_wiki"
issue: "https://github.com/2lazy2late/2lazy2late.github.io/issues/new"

timezone: "Asia/Seoul"

# https://kramdown.gettalong.org/rdoc/Kramdown/Options.html - smart_quotes
kramdown:
    smart_quotes: ["apos", "apos", "quot", "quot"]
